
@extends('master')

@section('konten')
    <!-- Select2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Select2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<body>
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Pelanggaran</h1>
            <ol class="breadcrumb mb-4">
              <li class="breadcrumb-item active">Tambah Jenis Pelanggaran</li>
            </ol>

                <form action="{{ route('pelanggarans.store') }}" method="POST" enctype="multipart/form-data">

                    @csrf

                    <div class="form-group mb-3">
                        <label class="font-weight-bold" for="pelanggaran_id">Pelanggaran:</label>
                        <select name="pelanggaran_id" class="select2 form-control" id="pelanggaran_id">
                            <!-- Options will be dynamically generated by Blade -->
                            @foreach($pelanggarans as $pelanggaran)
                            <option value="{{ $pelanggaran->id }}">{{ $pelanggaran->name }}</option>
                            @endforeach
                        </select>
                        @error('name')
                            <div class="alert alert-danger mt-2">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>

                <button type="submit" class="btn btn-md btn-primary me-3">SAVE</button>
                <button type="reset" class="btn btn-md btn-warning">RESET</button>
        </form>

    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
 </div>

</main>
@endsection

